# Configuration for areas to analyze for gaps in OLIMP questionnaire
# These sections will be analyzed to identify improvement opportunities

[gap_analysis]
target_sections = [
    "OBSZAR – LUDZIE I KOMPETENCJE", 
    "OBSZAR – ORGANIZACJA I PROCESY",
    "OBSZAR – PRODUKTY I USŁUGI"
]