[extract_answers]
extraction_prompt = """Analyze this Polish questionnaire PDF document and extract the structure in JSON format.

The document contains sections (OBSZAR), questions (PYTANIA), and answers (ODPOWIEDZI) with options A, B, C, D, E.
The selected answers are marked with "X" or "V" marks in the document. Look carefully at the visual layout:
- Each row represents a question
- Columns A, B, C, D, E contain the answer options
- The "X" or "V" mark appears in the column corresponding to the selected answer

CRITICAL: You must VERY CAREFULLY identify the exact column position of each "X" or "V" mark for every question. Take your time to:
1. Examine each row systematically from left to right
2. Identify which specific column (A, B, C, D, or E) contains the marking
3. Double-check the visual alignment between the mark and the column header
4. Be especially careful with marks that might appear between columns or slightly misaligned

IMPORTANT: The accuracy of answer extraction is crucial. Pay extremely close attention to which column contains the "X" or "V" mark for each question. This indicates the selected answer option.

Please extract:
1. Section names and their question counts
2. All questions within each section
3. All answer options (A, B, C, D, E) for each question
4. Which answer option is selected (marked with X or V) for each question - CAREFULLY examine the exact visual positioning and alignment of each mark with its corresponding column

Return the data in this JSON structure:
{{
  "questionnaire": "{questionnaire_type}",
  "questionnaire_title": "title of the questionnaire",
  "sections": [
    {{
      "section_name": "name of the section",
      "question_count": number_of_questions,
      "questions": [
        {{
          "question_text": "the question text",
          "answer_options": {{
            "A": "option A text",
            "B": "option B text", 
            "C": "option C text",
            "D": "option D text",
            "E": "option E text"
          }},
          "selected_answer": "A/B/C/D/E"
        }}
      ]
    }}
  ]
}}

Extract the data as JSON, making sure to correctly identify which column (A, B, C, D, or E) contains the "X" or "V" mark for each question.

FINAL CHECK: Before completing the extraction, systematically verify each selected_answer by re-examining the visual position of marks in the PDF to ensure 100% accuracy."""

[recommend]
recommendation_prompt = """Jesteś ekspertem ds. transformacji cyfrowej i implementacji AI w organizacjach. 

UWAGA: Wykorzystaj najnowsze, aktualne informacje o technologiach AI i najlepszych praktykach. 

Na podstawie analizy luk w obszarach OLIMP, przygotuj szczegółowy raport z rekomendacjami dla firmy, która chce płynnie przejść z obecnego stanu do poziomu E (maksymalnego) poprzez stany przejściowe.

Dane wejściowe to analiza luk w formacie JSON, która zawiera:
- Dla każdej sekcji (TECHNOLOGIA I INFRASTRUKTURA, LUDZIE I KOMPETENCJE, ORGANIZACJA I PROCESY)
- Dla każdego pytania: obecny poziom (present) i kroki do poziomu E (steps)
- Każdy poziom zawiera literę (A-E) i szczegółowy opis

STRUKTURA RAPORTU:
1. **Streszczenie wykonawcze**
   - Ogólna ocena obecnego stanu organizacji
   - Kluczowe obszary wymagające uwagi
   - Priorytety transformacji

2. **Analiza według obszarów**
   - Dla każdego obszaru (TECHNOLOGIA I INFRASTRUKTURA, LUDZIE I KOMPETENCJE, ORGANIZACJA I PROCESY):
     - Obecny stan i główne wyzwania
     - Rekomendowane ścieżki rozwoju
     - Konkretne działania do podjęcia

3. **Plan implementacji**
   - Faza 1 (0-6 miesięcy): Działania pilotażowe i podstawy
   - Faza 2 (6-18 miesięcy): Rozwój i skalowanie
   - Faza 3 (18-36 miesięcy): Optymalizacja i doskonałość

4. **Zasoby i budżet**
   - Szacowany budżet dla każdej fazy
   - Potrzebne zasoby ludzkie
   - Technologie i narzędzia do wdrożenia

5. **Wskaźniki sukcesu i monitoring**
   - KPI dla każdego obszaru
   - Sposoby mierzenia postępu
   - Punkty kontrolne

6. **Potencjalne korzyści i zyski**
   - Korzyści biznesowe z implementacji AI w każdym z obszarów
   - Szacowane oszczędności kosztów i wzrost efektywności
   - Przewaga konkurencyjna i nowe możliwości biznesowe
   - Długoterminowe korzyści strategiczne
   - Przykłady konkretnych ulepszeń procesów i produktów
   - Zwrot z inwestycji (ROI) i inne mierzalne korzyści

WYMAGANIA:
- Raport w języku polskim
- Konkretne, wykonalne rekomendacje
- Uwzględnienie specyfiki biznesowej
- Realistyczne timeline'y
- Fokus na płynne przejście między poziomami

Dane do analizy:
{gaps_data}

DODATKOWY KONTEKST:
Poniżej znajdują się odpowiedzi z jednego z kwestionariuszy (CLIMB_2), które mogą (ale nie muszą) być wykorzystane jako informacje uzupełniające do wygenerowania rekomendacji. Te dane mogą pomóc w lepszym zrozumieniu specyfiki organizacji i kontekstu biznesowego:

{supplementary_context}

Przygotuj profesjonalny raport w formacie Markdown."""